"""init

Revision ID: f50e89ab9941
Revises: 
Create Date: 2024-07-18 20:43:15.301852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50e89ab9941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('nuts3', sa.String(), nullable=True),
    sa.Column('nuts2', sa.String(), nullable=True),
    sa.Column('temperature_air', sa.Integer(), nullable=True),
    sa.Column('relative_humidity', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('wind_gust', sa.Integer(), nullable=True),
    sa.Column('atmospheric_pressure', sa.Integer(), nullable=True),
    sa.Column('relative_humidity_canopy', sa.Integer(), nullable=True),
    sa.Column('temperature_canopy', sa.Integer(), nullable=True),
    sa.Column('solar_irradiance_copernicus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('rule')
    op.drop_table('data')
    op.drop_table('action')
    # ### end Alembic commands ###
